/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoprogramadoi.views;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario1
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
   
    AgregarRaza tablaRaza;
    
    public MainForm() {
        initComponents();
       tablaRaza = new AgregarRaza();
       this.jMenuBar1.add(tablaRaza);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuAgregarRaza = new javax.swing.JMenu();
        jMenuItem3Raza = new javax.swing.JMenuItem();
        AgregarRazajMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenu5.setText("jMenu5");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("PrinciparFrame"); // NOI18N

        MenuAgregarRaza.setText("Administración Información Ganaderos");

        jMenuItem3Raza.setText("AgregarRaza");
        jMenuItem3Raza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3RazaActionPerformed(evt);
            }
        });
        MenuAgregarRaza.add(jMenuItem3Raza);

        AgregarRazajMenuItem.setText("AgregarGanadero");
        MenuAgregarRaza.add(AgregarRazajMenuItem);

        jMenuBar1.add(MenuAgregarRaza);

        jMenu2.setText("Administración Precios Ganado");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Recepción y Facturación Ganado");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Salir");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3RazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3RazaActionPerformed
        tablaRaza.setVisible(true);
    }//GEN-LAST:event_jMenuItem3RazaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AgregarRazajMenuItem;
    private javax.swing.JMenu MenuAgregarRaza;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3Raza;
    // End of variables declaration//GEN-END:variables
}
