/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoprogramadoi.views;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario1
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    AgregarGanadero agregarGanadero;
    AgregarRaza tablaRaza;
    AgregarGanado agregarGanado;
    
    public MainForm() {
       initComponents();
       
       agregarGanadero=new AgregarGanadero();
       this.jMenuBar1.add(agregarGanadero);
       tablaRaza = new AgregarRaza();
       this.jMenuBar1.add(tablaRaza);
       agregarGanado=new AgregarGanado();
       this.jMenuBar1.add(agregarGanado);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuAgregarRaza = new javax.swing.JMenu();
        AgregarGanadero = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        AgregarRazas = new javax.swing.JMenuItem();
        AgregarGanado = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenu();
        Cerrar = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu5.setText("jMenu5");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("PrinciparFrame"); // NOI18N

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        MenuAgregarRaza.setText("Administración Información Ganaderos");

        AgregarGanadero.setText("Ganadero");
        AgregarGanadero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarGanaderoActionPerformed(evt);
            }
        });
        MenuAgregarRaza.add(AgregarGanadero);

        jMenuBar1.add(MenuAgregarRaza);

        jMenu2.setText("Administración Ganado");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        AgregarRazas.setText("Razas");
        AgregarRazas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarRazasActionPerformed(evt);
            }
        });
        jMenu2.add(AgregarRazas);

        AgregarGanado.setText("Ganado");
        AgregarGanado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarGanadoActionPerformed(evt);
            }
        });
        jMenu2.add(AgregarGanado);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Facturación Ganado");

        jMenuItem5.setText("Consulta Factura");
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        Cerrar.setText("Cerrar el Sistema");
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });
        Salir.add(Cerrar);
        Cerrar.getAccessibleContext().setAccessibleName("Cerrar el Sistema");

        jMenuBar1.add(Salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarGanaderoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarGanaderoActionPerformed
        agregarGanadero.setVisible(true);
    }//GEN-LAST:event_AgregarGanaderoActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        
    }//GEN-LAST:event_SalirActionPerformed

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed
        JOptionPane.showMessageDialog(null,"Gracias por usar el sistema\n¡Hasta pronto!");
        System.exit(0);
    }//GEN-LAST:event_CerrarActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void AgregarRazasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarRazasActionPerformed
        tablaRaza.setVisible(true);
    }//GEN-LAST:event_AgregarRazasActionPerformed

    private void AgregarGanadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarGanadoActionPerformed
        agregarGanado.setVisible(true);
    }//GEN-LAST:event_AgregarGanadoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AgregarGanadero;
    private javax.swing.JMenuItem AgregarGanado;
    private javax.swing.JMenuItem AgregarRazas;
    private javax.swing.JMenuItem Cerrar;
    private javax.swing.JMenu MenuAgregarRaza;
    private javax.swing.JMenu Salir;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    // End of variables declaration//GEN-END:variables
}
